[package]
name = "fflate"
version = "0.0.1"
authors = ["Arjun Barrett <arjunbarrett@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "^1.4.0"

[profile.release]
opt-level = "s"
lto = true

[lib]
crate-type = ["cdylib", "rlib"]