[package]
name = "fflate"
version = "0.0.1"
authors = ["Arjun Barrett <arjunbarrett@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "^1.4.0"
wasm-bindgen = "^0.2.69"
wee_alloc = "^0.4.5"

[profile.release]
opt-level = "s"

[lib]
crate-type = ["cdylib", "rlib"]